export { default as image1 } from "../assets/image11.png";
export { default as image2 } from "../assets/image7.png";
export { default as image3 } from "../assets/image10.png";
export { default as logo1 } from "../assets/logo1.png";
export { default as logo2 } from "../assets/logo2.png";
export { default as logo3 } from "../assets/logo3.png";
export {default as vector1} from "../assets/Vector1.png";
export {default as vector2} from "../assets/Vector2.png";
export {default as vector3} from "../assets/Vector3.png";
export {default as vector4} from "../assets/Vector4.png";
